# Generated by Django 2.2.3 on 2019-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('question', 'Post a Question'), ('city', 'Around the City'), ('secret', 'Secret Post'), ('none', 'None')], default='none', max_length=15),
        ),
    ]
