# Generated by Django 2.2.3 on 2019-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='im',
            field=models.ImageField(default='default.jpeg', upload_to='post_pics'),
        ),
    ]
