# Generated by Django 2.2.3 on 2019-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='im',
            field=models.ImageField(default=None, upload_to='post_pics'),
        ),
    ]
