# Generated by Django 2.2.3 on 2019-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190722_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='im',
            field=models.ImageField(upload_to='post_pics'),
        ),
    ]
