# Generated by Django 2.2.3 on 2019-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='post_pics'),
        ),
    ]
