# Generated by Django 2.2.3 on 2019-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190724_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='apple-black-and-white-brick-wall-169573.jpg', upload_to='post_pics'),
        ),
    ]
