# Generated by Django 2.2.3 on 2019-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190724_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ImageField(null=True, upload_to='post_videos/'),
        ),
    ]
